version: 2

sources:
  - name: chess_raw
    project: checkmate-453316
    tables:
      - name: games

models:
  - name: calendar
    description: "Calendar table with wide-combination of values and formats accounting for days/weeks/months/quarters/years"
    columns:
      - name: cal_date
        description: "The calendar date represented at the daily granularity"
      - name: day
        description: "Day Number"
      - name: week
        description: "Week Number (Starting Sunday)"
      - name: iso_week
        description: "Week Number (Starting Monday)"
      - name: month
        description: "Month Number"
      - name: quarter
        description: "Quarter Number"
      - name: year
        description: "Year Number"
      - name: month_name
        description: "Name of Month"

      - name: year_quarter
        description: "Year and Quarter based on cal_date"
      - name: quarter_start_date
        description: "Quarter Start Date"
      - name: quarter_end_date
        description: "Quarter End Date"
      - name: month_start_date
        description: "Month Start Date"
      - name: month_end_date
        description: "Month End Date"
      - name: month_year_short
        description: "Month Year in the format %b-%y"
      - name: month_year_full
        description: "Month Year in the format %B-%Y"
      - name: iso_week_desc
        description: "ISO Week Number in the format 'Week' {number}"
      - name: iso_week_start_date
        description: "ISO Week Start Date (Starting Monday)"
      - name: iso_week_end_date
        description: "ISO Week End Date (Ending Sunday)"
      - name: week_number_desc
        description: "Week Number in the format 'Week' {number}"
      - name: week_start_date
        description: "Week End Date (Starting Sunday)"
      - name: week_end_date
        description: "Week End Date (Ending Saturday)"

      - name: flag_current_month
        description: "Flag days in the current month"
      - name: flag_1st_previous_month
        description: "Flag days in the previous month"
      - name: flag_2nd_previous_month
        description: "Flag days in the month before the previous month"
      - name: flag_current_month_last_year
        description: "Flag days in the current month from last year"
      - name: flag_1st_previous_month_last_year
        description: "Flag days in the previous month from last year"
      - name: flag_2nd_previous_month_last_year
        description: "Flag days in the month before the previous month from last year"

      - name: flag_current_quarter
        description: "Flag days in the current calendar quarter"
      - name: flag_1st_previous_quarter
        description: "Flag days in the previous calendar quarter"
      - name: flag_2nd_previous_quarter
        description: "Flag days in the calendar quarter before the previous one"
      - name: flag_current_quarter_last_year
        description: "Flag days in the current calendar quarter from last year"
      - name: flag_1st_previous_quarter_last_year
        description: "Flag days in the previous calendar quarter from last year"
      - name: flag_2nd_previous_quarter_last_year
        description: "Flag days in the calendar quarter before the previous one from last year"

      - name: flag_current_week
        description: "Flag days in the current calendar week (starting Sunday)"
      - name: flag_1st_previous_week
        description: "Flag days in the previous calendar week (starting Sunday)"
      - name: flag_2nd_previous_week
        description: "Flag days in the calendar week before the previous one (starting Sunday)"
      - name: flag_current_week_last_year
        description: "Flag days in the current calendar week from last year (starting Sunday)"
      - name: flag_1st_previous_week_last_year
        description: "Flag days in the previous calendar week from last year (starting Sunday)"
      - name: flag_2nd_previous_week_last_year
        description: "Flag days in the calendar week before the previous one from last year (starting Sunday)"

      - name: flag_current_iso_week
        description: "Flag days in the current ISO week (starting Monday)"
      - name: flag_1st_previous_iso_week
        description: "Flag days in the previous ISO week (starting Monday)"
      - name: flag_2nd_previous_iso_week
        description: "Flag days in the ISO week before the previous one (starting Monday)"
      - name: flag_current_iso_week_last_year
        description: "Flag days in the current ISO week from last year (starting Monday)"
      - name: flag_1st_previous_iso_week_last_year
        description: "Flag days in the previous ISO week from last year (starting Monday)"
      - name: flag_2nd_previous_iso_week_last_year
        description: "Flag days in the ISO week before the previous one from last year (starting Monday)"

      - name: flag_current_year
        description: "Flag days in the current year"
      - name: flag_1st_previous_year
        description: "Flag days in the previous year"
      - name: flag_2nd_previous_year
        description: "Flag days in the year before the previous year"

      - name: flag_current_last_12_months
        description: "Flag days in the last 12 months from today"
      - name: flag_previous_last_12_months
        description: "Flag days in the last 12 months from today's date last year"

  - name: stg__player_games
    description: >
      Stage model that transforms raw chess game data into a player-level view, 
      with one row per player per game (both white and black perspectives). 
      Includes standardizations for result classification (win/loss/draw), 
      basic game metadata, and parsed opening names. This model supports 
      incremental loads by game date for efficient backfills.
    columns:
      - name: game_id
        description: Unique identifier of the chess game.
      - name: game_date
        description: The date the game was played, used for partitioning.
      - name: username
        description: Username of the player (either white or black).
      - name: rating
        description: Player's rating at the time the game was played.
      - name: piece_color
        description: Color the player was playing in the game (`white` or `black`).
      - name: time_class
        description: Time control category of the game (e.g., blitz, rapid, bullet).
      - name: rules
        description: Game variant or ruleset (typically `chess` for standard games).
      - name: raw_result
        description: Raw result string as recorded in the source data (e.g., win, resigned, stalemate).
      - name: rated
        description: Boolean flag indicating whether the game was rated.
      - name: win_loss_draw
        description: Normalized result classification with values `win`, `loss`, or `draw` based on `raw_result`.
      - name: opening_line
        description: Full ECO-style opening line (e.g., "1.e4 e5 2.Nf3 Nc6").
      - name: opening
        description: Cleaned opening name with move numbers and continuation symbols removed, for grouping purposes.
      - name: accuracy
        description: Accuracy score for the player in the game, as provided by the source.

  - name: quarterly_chess_player_metrics
    description: >
      Aggregates player game statistics by quarter, time class, and opening archetype.
      This model provides breakdowns of game outcomes (win/loss/draw) and average accuracy
      by piece color (white/black) for rated standard chess games. It uses calendar and
      opening mapping tables to enrich the game data, and filters to only include recent
      games based on configurable date logic.
    columns:
      - name: quarter_start_date
        description: The first calendar date of the quarter during which the games were played.
      - name: year_quarter
        description: The year and quarter in the format YYYYQn (e.g., 2024Q1).
      - name: username
        description: Chess.com username of the player.
      - name: time_class
        description: Time control classification of the game (e.g., blitz, rapid, bullet).
      - name: opening_archetype
        description: High-level categorization of the opening played. Defaults to "Mapping Failed" if unmapped.
      - name: total_games
        description: Total number of rated standard chess games played by the user in the quarter under the given opening archetype and time class.
      - name: white_win_count
        description: Number of games won while playing as white.
      - name: white_loss_count
        description: Number of games lost while playing as white.
      - name: white_draw_count
        description: Number of games drawn while playing as white.
      - name: white_accuracy
        description: Average accuracy in games played as white.
      - name: black_win_count
        description: Number of games won while playing as black.
      - name: black_loss_count
        description: Number of games lost while playing as black.
      - name: black_draw_count
        description: Number of games drawn while playing as black.
      - name: black_accuracy
        description: Average accuracy in games played as black.

  - name: weekly_chess_player_metrics
    description: >
      Weekly aggregate statistics of rated standard chess games by player, piece color, and time class.
      This model calculates performance metrics such as win/loss/draw counts, accuracy, and rating,
      separated by white and black games. It uses the calendar table to align games to ISO week start dates
      and is designed for incremental refresh with weekly partitioning and clustering.
    columns:
      - name: week_start_date
        description: The ISO calendar start date (Monday) for the week in which the games were played.
      - name: week_number
        description: The ISO week label in the format YYYY-WW (e.g., 2024-W05).
      - name: username
        description: Chess.com username of the player.
      - name: time_class
        description: Time control classification of the game (e.g., blitz, rapid, bullet).
      - name: avg_rating
        description: Average rating of the player across all games played in the week.
      - name: total_games
        description: Total number of rated standard chess games played in the week by the user for the given time class.
      - name: white_win_count
        description: Number of games won while playing as white.
      - name: white_loss_count
        description: Number of games lost while playing as white.
      - name: white_draw_count
        description: Number of games drawn while playing as white.
      - name: white_accuracy
        description: Average move accuracy in games played as white.
      - name: black_win_count
        description: Number of games won while playing as black.
      - name: black_loss_count
        description: Number of games lost while playing as black.
      - name: black_draw_count
        description: Number of games drawn while playing as black.
      - name: black_accuracy
        description: Average move accuracy in games played as black.
