version: 2

sources:
  - name: chess_raw
    project: checkmate-453316
    tables:
      - name: games

models:
  - name: calendar
    description: "Calendar table with wide-combination of values and formats accounting for days/weeks/months"
    columns:
      - name: cal_date
        description: "The calendar date at day-level"
      - name: day_digit
        description: "Day Number"
      - name: month_digit
        description: "Month Number"
      - name: year_digit
        description: "Year Number"
      - name: month_name
        description: "Month Name"
      - name: month_start_date
        description: "Month Start Date"
      - name: month_end_date
        description: "Month End Date"
      - name: month_year_type1
        description: "Month Year in the format %b-%y"
      - name: month_year_type2
        description: "Month Year in the format %B-%Y"
      - name: iso_week_number_type1
        description: "ISO Week Number in the format 'Week' {number}"
      - name: iso_week_number_type2
        description: "ISO Week Number in the format {number}"
      - name: iso_week_start
        description: "ISO Week Start Date (Starting Monday)"
      - name: iso_week_end
        description: "ISO Week End Date (Ending Sunday)"
      - name: week_number_type1
        description: "Week Number in the format 'Week' {number}"
      - name: week_number_type2
        description: "Week Number in the format {number}"
      - name: week_start_date
        description: "Week End Date (Starting Sunday)"
      - name: week_end_date
        description: "Week End Date (Ending Saturday)"
      - name: flag_current_month
        description: "Flag days in the current month"
      - name: flag_1st_previous_month
        description: "Flag days in the previous month"
      - name: flag_2nd_previous_month
        description: "Flag days in the month before the previous month"
      - name: flag_current_month_last_year
        description: "Flag days in the current month from last year"
      - name: flag_1st_previous_month_last_year
        description: "Flag days in the previous month from last year"
      - name: flag_2nd_previous_month_last_year
        description: "Flag days in the month before the previous month from last year"
      - name: flag_current_year
        description: "Flag days in the current year"
      - name: flag_1st_previous_year
        description: "Flag days in the previous year"
      - name: flag_2nd_previous_year
        description: "Flag days in the year before the previous year"
      - name: flag_current_last_12_months
        description: "Flag days in the last 12 months from today"
      - name: flag_previous_last_12_months
        description: "Flag days in the last 12 months from todays date last year" 
