#!/bin/bash
BASE_DIRECTORY="$(pwd)"
source $BASE_DIRECTORY/variables

docker run --rm \
  -v "$PWD/sa.json:/creds/sa.json:ro" \
  -e GOOGLE_APPLICATION_CREDENTIALS=/creds/sa.json \
  $AR_TYPE/$GCP_PROJECT/$AR_REPO/$IMAGE_NAME:latest
