name: Terraform Deployment

on:
  push:
    branches:
      - main

env:
    PROJECT_ID: "checkmate-453316"

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # Required for OIDC

    steps:
    - id: 'checkout'
      name: Checkout code
      uses: actions/checkout@v4

    - id: 'auth'
      name: Authenticate with GCP
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: "projects/810099024571/locations/global/workloadIdentityPools/github-pool/attribute.repository/Filpill/chess_analysis"
        service_account: "github-actions-sa@checkmate-453316.iam.gserviceaccount.com"

    - id: 'install'
      name: Install Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: latest

    - id: 'init'
      name: Terraform Init
      run: terraform init

    - id: 'plan'
      name: Terraform Plan
      run: terraform plan

    - id: 'apply'
      name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve
